export type   AntropometriaHistorico = {
    dados_geral_id: number;
    paciente_id: number;
    id_bioimpedancia: number;
    dados_id: number;
    faixa_etaria: number;
    data_registro: string;
  }
  
  export type  AntropometriaAdulto  = {
    id: number;
    id_paciente: number;
    dataa: Date;
    data_atualizacao: Date | null;
    peso: string | null;
    altura: string | null;
    idade: string | null;
    ombro: string | null;
    peitoral: string | null;
    cintura: string | null;
    abdomen: string | null;
    quadril: string | null;
    panturrilha_direita: string | null;
    panturrilha_esquerda: string | null;
    pescoco: string | null;
    punho_esquerdo: string | null;
    punho_direito: string | null;
    coxa_proximal_direita: string | null;
    coxa_proximal_esquerda: string | null;
    coxa_medial_direita: string | null;
    coxa_medial_esquerda: string | null;
    coxa_distal_direita: string | null;
    coxa_distal_esquerda: string | null;
    braco_relaxado_direito: string | null;
    braco_relaxado_esquerdo: string | null;
    braco_contraido_direito: string | null;
    braco_contraido_esquerdo: string | null;
    antebraco_esquerdo: string | null;
    antebraco_direito: string | null;
    diametro_estilo_ulnar: string | null;
    diametro_bicondio_femural: string | null;
    protocolo: string | null;
    biceps: string | null;
    triceps: string | null;
    axilar_media: string | null;
    torax: string | null;
    abdominal: string | null;
    suprailiaca: string | null;
    subescapular: string | null;
    coxa: string | null;
    panturrilha_media: string | null;
    peso_osseo: string | null;
    peso_residual: string | null;
    imc: string | null;
    peso_gordo: string | null;
    peso_magro: string | null;
    perc_massa_gorda: string | null;
    perc_massa_magra: string | null;
    soma_dobras: string | null;
    classificacao_pollock: string | null;
    pesoidealimc: string | null;
    densidade: string | null;
    riscocardio: string | null;
    massa_gorda_kg_recomendado: string | null;
    massa_gorda_kg_classificacao: string | null;
    massa_gorda_percentual_recomendado: string | null;
    massa_livre_de_gordura_kg_recomendado: string | null;
    massa_livre_de_gordura_kg_classificacao: string | null;
    massa_livre_de_gordura_percentual_recomendado: string | null;
    massa_livre_de_gordura_percentual_classificacao: string | null;
    massa_muscular_kg_recomendado: string | null;
    massa_muscular_kg_classificacao: string | null;
    massa_muscular_percentual_recomendado: string | null;
    massa_muscular_percentual_classificacao: string | null;
    massa_livre_de_gordura_kg: string | null;
    massa_livre_de_gordura_percentual: string | null;
    peso_recomendado: string | null;
    peso_classificacao: string | null;
    imc_classificacao: string | null;
  }
  
