export type Food = {
  id: number,
  descricaoDoAlimento: string,
  medidaCaseira1: string,
  gramas1: string,
  medidaCaseira2: string,
  gramas2: string,
  medidaCaseira3: string,
  gramas3: string,
  medidaCaseira4: string,
  gramas4: string,
  medidaCaseira5: string,
  gramas5: number,
  energia: number,
  proteina: number,
  lipideos: number,
  colesterol: string,
  carboidrato: number,
  fibra_alimentar: string,
  cinzas: string,
  calcio: string,
  magnesio: string,
  manganes: string,
  fosforo: string,
  ferro: string,
  sodio: string,
  potassio: string,
  cobre: string,
  zinco: string,
  retinol: string,
  tiamina_vitamina_b1: string,
  riboflavina_vitamina_b2: string,
  piridoxina_vitamina_b6: string,
  niacina_vitamina_b3: string,
  vitamina_c: string,
  acidos_graxos_saturados: string,
  acidos_graxos_monoinsaturados: string,
  acidos_graxos_poliinsaturados: string,
  tabela: string,
  grupo_d: number,
  id_alimento_base: number,
  key: string
};

export type ShoppingListFood = {
  id?: number,
  key?: string,
  nome: string,
  gramas_7: number,
  gramas_15: number,
  gramas_30: number,
  id_plano: number,
  is_user_input: number,
  update_list: number
}

export type MedidaCaseira = {
  nome: string,
  gramas: number,
}