export const symptons = [
  {"id": 1, "category": "Músculos e articulações", "symptom": "Artrites ou artrose"},
  {"id": 2, "category": "Músculos e articulações", "symptom": "Dores articulares"},
  {"id": 3, "category": "Músculos e articulações", "symptom": "Sensação de fraqueza ou cansaço"},
  {"id": 4, "category": "Músculos e articulações", "symptom": "Dores musculares"},
  {"id": 5, "category": "Músculos e articulações", "symptom": "Rigidez ou limitação dos movimentos"},
  {"id": 6, "category": "Saúde bucal e garganta", "symptom": "Aftas"},
  {"id": 7, "category": "Saúde bucal e garganta", "symptom": "Dor de garganta, ronquidão ou perda de voz"},
  {"id": 8, "category": "Saúde bucal e garganta", "symptom": "Língua, gengivas ou lábios inchados/descoloridos"},
  {"id": 9, "category": "Saúde bucal e garganta", "symptom": "Tosse crônica"},
  {"id": 10, "category": "Saúde bucal e garganta", "symptom": "Frequente necessidade de limpar a garganta"},
  {"id": 11, "category": "Cabeça", "symptom": "Sensação de desmaio"},
  {"id": 12, "category": "Cabeça", "symptom": "Insônia"},
  {"id": 13, "category": "Cabeça", "symptom": "Dor de cabeça"},
  {"id": 14, "category": "Cabeça", "symptom": "Tonturas"},
  {"id": 15, "category": "Coração", "symptom": "Batidas irregulares ou falhando"},
  {"id": 16, "category": "Coração", "symptom": "Dor no peito"},
  {"id": 17, "category": "Coração", "symptom": "Batidas rápidas demais"},
  {"id": 18, "category": "Emoções", "symptom": "Mudanças de humor / mau-humor matinal"},
  {"id": 19, "category": "Emoções", "symptom": "Raiva, irritabilidade, agressividade"},
  {"id": 20, "category": "Emoções", "symptom": "Ansiedade, medo, nervosismo"},
  {"id": 21, "category": "Emoções", "symptom": "Depressão"},
  {"id": 22, "category": "Energia", "symptom": "Apatia, letargia"},
  {"id": 23, "category": "Energia", "symptom": "Dificuldade em descansar, relaxar"},
  {"id": 24, "category": "Energia", "symptom": "Fadiga, moleza"},
  {"id": 25, "category": "Energia", "symptom": "Hiperatividade"},
  {"id": 26, "category": "Mente", "symptom": "Concentração ruim"},
  {"id": 27, "category": "Mente", "symptom": "Confusão mental, compreensão ruim"},
  {"id": 28, "category": "Mente", "symptom": "Memória ruim"},
  {"id": 29, "category": "Mente", "symptom": "Fala com repetição de sons ou palavras, com várias pausas involuntárias"},
  {"id": 30, "category": "Mente", "symptom": "Dificuldade de tomar decisões"},
  {"id": 31, "category": "Mente", "symptom": "Fraca coordenação motora"},
  {"id": 32, "category": "Mente", "symptom": "Problemas de aprendizagem"},
  {"id": 33, "category": "Mente", "symptom": "Pronuncia palavras de forma indistinta, confusa"},
  {"id": 34, "category": "Nariz", "symptom": "Ataques de espirros"},
  {"id": 35, "category": "Nariz", "symptom": "Excessiva formação de muco"},
  {"id": 36, "category": "Nariz", "symptom": "Corrimento nasal, espirros, lacrimejamento e coceira dos olhos (todos juntos)"},
  {"id": 37, "category": "Nariz", "symptom": "Entupido"},
  {"id": 38, "category": "Nariz", "symptom": "Problemas de seios nasais (Sinusite)"},
  {"id": 39, "category": "Olhos", "symptom": "Bolsas ou olheiras abaixo dos olhos"},
  {"id": 40, "category": "Olhos", "symptom": "Visão borrada ou em túnel (não incluiu miopia ou astigmatismo)"},
  {"id": 41, "category": "Olhos", "symptom": "Inchados, vermelhos ou com cílios colando"},
  {"id": 42, "category": "Olhos", "symptom": "Lacrimejantes ou coçando"},
  {"id": 43, "category": "Ouvidos", "symptom": "Coceira"},
  {"id": 44, "category": "Ouvidos", "symptom": "Retirada de fluido purulento de ouvido"},
  {"id": 45, "category": "Ouvidos", "symptom": "Dores de ouvido, infecções auditivas"},
  {"id": 46, "category": "Ouvidos", "symptom": "Zunido, perda de audição"},
  {"id": 47, "category": "Pele", "symptom": "Acne"},
  {"id": 48, "category": "Pele", "symptom": "Perda de cabelo"},
  {"id": 49, "category": "Pele", "symptom": "Vermelhidão, calorões"},
  {"id": 50, "category": "Pele", "symptom": "Feridas que coçam, erupções, pele seca"},
  {"id": 51, "category": "Pele", "symptom": "Suor excessivo"},
  {"id": 52, "category": "Pulmões", "symptom": "Asma, bronquite"},
  {"id": 53, "category": "Pulmões", "symptom": "Dificuldade para respirar"},
  {"id": 54, "category": "Pulmões", "symptom": "Congestão no peito"},
  {"id": 55, "category": "Pulmões", "symptom": "Pouco fôlego"},
  {"id": 56, "category": "Trato digestivo", "symptom": "Arrotos e/ou gases intestinais"},
  {"id": 57, "category": "Trato digestivo", "symptom": "Constipação / prisão de ventre"},
  {"id": 58, "category": "Trato digestivo", "symptom": "Dor estomacal / intestinal"},
  {"id": 59, "category": "Trato digestivo", "symptom": "Sente-se inchado / com abdômen distendido"},
  {"id": 60, "category": "Trato digestivo", "symptom": "Azia"},
  {"id": 61, "category": "Trato digestivo", "symptom": "Diarreia"},
  {"id": 62, "category": "Trato digestivo", "symptom": "Náuseas, vômito"},
  {"id": 63, "category": "Outros", "symptom": "Coceira genital ou corrimento"},
  {"id": 64, "category": "Outros", "symptom": "Frequentemente doente"},
  {"id": 65, "category": "Outros", "symptom": "Edema / Inchaço - Pés / Pernas / Mãos"},
  {"id": 66, "category": "Outros", "symptom": "Frequentemente ou urgentemente vontade de urinar"}
]
