export const timezones = [
  { value: "Asia/Dhaka", label: "(UTC+06:00) Bangladesh" },
  { value: "Europe/Brussels", label: "(UTC+02:00) Romance" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Europe/Sofia", label: "(UTC+03:00) FLE" },
  { value: "Europe/Belgrade", label: "(UTC+02:00) Central Europe" },
  { value: "America/Barbados", label: "(UTC-04:00) SA Western" },
  { value: "Pacific/Wallis", label: "(UTC+12:00) UTC+12" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Atlantic/Bermuda", label: "(UTC-03:00) Atlantic" },
  { value: "Asia/Brunei", label: "(UTC+08:00) Singapore" },
  { value: "America/La_Paz", label: "(UTC-04:00) SA Western" },
  { value: "Asia/Tokyo", label: "(UTC+09:00) Tokyo" },
  { value: "Africa/Maputo", label: "(UTC+02:00) South Africa" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "Asia/Thimphu", label: "(UTC+06:00) Bangladesh" },
  { value: "America/Jamaica", label: "(UTC-05:00) SA Pacific" },
  { value: "Asia/Amman", label: "(UTC+02:00) Jordan" },
  { value: "Pacific/Apia", label: "(UTC+14:00) Samoa" },
  { value: "America/Curacao", label: "(UTC-04:00) SA Western" },
  { value: "America/Noronha", label: "(UTC-02:00) UTC-02" },
  { value: "America/Belem", label: "(UTC-03:00) Belem" },
  { value: "America/Fortaleza", label: "(UTC-03:00) Fortaleza" },
  { value: "America/Recife", label: "(UTC-03:00) Recife" },
  { value: "America/Araguaina", label: "(UTC-03:00) Araguaina" },
  { value: "America/Maceio", label: "(UTC-03:00) Maceio" },
  { value: "America/Bahia", label: "(UTC-03:00) Bahia" },
  { value: "America/São_Paulo", label: "(UTC-03:00) Sao Paulo" },
  { value: "America/Campo_Grande", label: "(UTC-04:00) Campo Grande/MS" },
  { value: "America/Cuiaba", label: "(UTC-04:00) Cuiaba" },
  { value: "America/Porto_Velho", label: "(UTC-04:00) Velho" },
  { value: "America/Boa_Vista", label: "(UTC-04:00) Boa Vista" },
  { value: "America/Manaus", label: "(UTC-04:00) Manaus" },
  { value: "America/Rio_Branco", label: "(UTC-05:00) Rio Branco" },
  { value: "America/Nassau", label: "(UTC-04:00) Eastern" },
  { value: "Europe/London", label: "(UTC+01:00) GMT" },
  { value: "Europe/Minsk", label: "(UTC+03:00) Belarus" },
  { value: "America/Belize", label: "(UTC-06:00) Central America" },
  { value: "Europe/Kaliningrad", label: "(UTC+02:00) Kaliningrad" },
  { value: "Europe/Moscow", label: "(UTC+03:00) Russian" },
  { value: "Europe/Simferopol", label: "(UTC+03:00) Russian" },
  { value: "Europe/Volgograd", label: "(UTC+03:00) Russian" },
  { value: "Europe/Samara", label: "(UTC+04:00) Russia Zone 3" },
  { value: "Asia/Yekaterinburg", label: "(UTC+05:00) Ekaterinburg" },
  { value: "Asia/Omsk", label: "(UTC+06:00) N. Central Asia" },
  { value: "Asia/Novosibirsk", label: "(UTC+06:00) N. Central Asia" },
  { value: "Asia/Novokuznetsk", label: "(UTC+07:00) North Asia" },
  { value: "Asia/Krasnoyarsk", label: "(UTC+07:00) North Asia" },
  { value: "Asia/Irkutsk", label: "(UTC+08:00) North Asia East" },
  { value: "Asia/Chita", label: "(UTC+09:00) Yakutsk" },
  { value: "Asia/Yakutsk", label: "(UTC+09:00) Yakutsk" },
  { value: "Asia/Khandyga", label: "(UTC+09:00) Yakutsk" },
  { value: "Asia/Vladivostok", label: "(UTC+10:00) Vladivostok" },
  { value: "Asia/Ust-Nera", label: "(UTC+10:00) Vladivostok" },
  { value: "Asia/Magadan", label: "(UTC+10:00) Magadan" },
  { value: "Asia/Sakhalin", label: "(UTC+11:00) Vladivostok" },
  { value: "Asia/Srednekolymsk", label: "(UTC+11:00) Russia Zone 10" },
  { value: "Asia/Kamchatka", label: "(UTC+12:00) Russia Zone 11" },
  { value: "Asia/Anadyr", label: "(UTC+12:00) Russia Zone 11" },
  { value: "Africa/Maputo", label: "(UTC+02:00) South Africa" },
  { value: "Europe/Belgrade", label: "(UTC+02:00) Central Europe" },
  { value: "Europe/Vilnius", label: "(UTC+03:00) FLE" },
  { value: "Indian/Reunion", label: "(UTC+04:00) Mauritius" },
  { value: "Europe/Luxembourg", label: "(UTC+02:00) W. Europe" },
  { value: "Africa/Monrovia", label: "(UTC+00:00) Greenwich" },
  { value: "Europe/Bucharest", label: "(UTC+03:00) GTB" },
  { value: "Pacific/Fakaofo", label: "(UTC+13:00) Tonga" },
  { value: "Africa/Bissau", label: "(UTC+00:00) Greenwich" },
  { value: "Pacific/Guam", label: "(UTC+10:00) West Pacific" },
  { value: "America/Guatemala", label: "(UTC-06:00) Central America" },
  { value: "Europe/Athens", label: "(UTC+03:00) GTB" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Asia/Qatar", label: "(UTC+03:00) Arab" },
  { value: "America/Guyana", label: "(UTC-04:00) SA Western" },
  { value: "Europe/London", label: "(UTC+01:00) GMT" },
  { value: "America/Cayenne", label: "(UTC-03:00) SA Eastern" },
  { value: "Asia/Tbilisi", label: "(UTC+04:00) Georgian" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Europe/London", label: "(UTC+01:00) GMT" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "America/Godthab", label: "(UTC-02:00) Greenland" },
  { value: "America/Danmarkshavn", label: "(UTC+00:00) UTC" },
  { value: "America/Scoresbysund", label: "(UTC+00:00) Azores" },
  { value: "America/Thule", label: "(UTC-03:00) Atlantic" },
  { value: "Europe/Gibraltar", label: "(UTC+02:00) W. Europe" },
  { value: "Africa/Accra", label: "(UTC+00:00) Greenwich" },
  { value: "Asia/Dubai", label: "(UTC+04:00) Arabian" },
  { value: "Africa/Maputo", label: "(UTC+02:00) South Africa" },
  { value: "Europe/Belgrade", label: "(UTC+02:00) Central Europe" },
  { value: "America/Port-au-Prince", label: "(UTC-05:00) Eastern" },
  { value: "Europe/Budapest", label: "(UTC+02:00) Central Europe" },
  { value: "Asia/Hong_Kong", label: "(UTC+08:00) China" },
  { value: "America/Tegucigalpa", label: "(UTC-06:00) Central America" },
  { value: "Europe/Riga", label: "(UTC+03:00) FLE" },
  { value: "Europe/Andorra", label: "(UTC+02:00) W. Europe" },
  { value: "America/Puerto_Rico", label: "(UTC-04:00) SA Western" },
  { value: "Asia/Gaza", label: "(UTC+03:00) Palestine Time" },
  { value: "Pacific/Palau", label: "(UTC+09:00) Tokyo" },
  { value: "Europe/Lisbon", label: "(UTC+01:00) Lisbon" },
  { value: "Atlantic/Azores", label: "(UTC+00:00) Azores" },
  { value: "Asia/Seoul", label: "(UTC+09:00) Korea" },
  { value: "America/Asuncion", label: "(UTC-04:00) Paraguay" },
  { value: "Asia/Baghdad", label: "(UTC+03:00) Arabic" },
  { value: "America/Panama", label: "(UTC-05:00) SA Pacific" },
  { value: "Pacific/Tahiti", label: "(UTC-10:00) Hawaiian" },
  { value: "Pacific/Port_Moresby", label: "(UTC+10:00) West Pacific" },
  { value: "Pacific/Bougainville", label: "(UTC+11:00) Central Pacific" },
  { value: "America/Lima", label: "(UTC-05:00) SA Pacific" },
  { value: "Asia/Karachi", label: "(UTC+05:00) Pakistan" },
  { value: "Asia/Manila", label: "(UTC+08:00) Singapore" },
  { value: "Pacific/Pitcairn", label: "(UTC-08:00) Pitcairn Time" },
  { value: "Europe/Warsaw", label: "(UTC+02:00) Central European" },
  { value: "America/Miquelon", label: "(UTC-02:00) Miquelon Time" },
  { value: "Africa/Maputo", label: "(UTC+02:00) South Africa" },
  { value: "Africa/El_Aaiun", label: "(UTC+00:00) Morocco" },
  { value: "Europe/Tallinn", label: "(UTC+03:00) FLE" },
  { value: "Africa/Cairo", label: "(UTC+02:00) Egypt" },
  { value: "Africa/Johannesburg", label: "(UTC+02:00) South Africa" },
  { value: "America/Guayaquil", label: "(UTC-05:00) SA Pacific" },
  { value: "Pacific/Galapagos", label: "(UTC-06:00) Central America" },
  { value: "Europe/Tirane", label: "(UTC+02:00) Central Europe" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "Asia/Almaty", label: "(UTC+06:00) Almaty" },
  { value: "Asia/Aqtobe", label: "(UTC+05:00) Aqtobe" },
  { value: "Asia/Aqtau", label: "(UTC+05:00) Aqtau" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "Africa/Maputo", label: "(UTC+02:00) South Africa" },
  { value: "America/Panama", label: "(UTC-05:00) SA Pacific" },
  { value: "Europe/Madrid", label: "(UTC+02:00) Madrid" },
  { value: "Africa/Ceuta", label: "(UTC+02:00) Ceuta" },
  { value: "Atlantic/Canary", label: "(UTC+01:00) GMT" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "Europe/Belgrade", label: "(UTC+02:00) Central Europe" },
  { value: "Europe/Chisinau", label: "(UTC+03:00) E. Europe" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Africa/Casablanca", label: "(UTC+00:00) Morocco" },
  { value: "Europe/Monaco", label: "(UTC+02:00) W. Europe" },
  { value: "Asia/Tashkent", label: "(UTC+05:00) Tashkent" },
  { value: "Asia/Rangoon", label: "(UTC+06:30) Myanmar" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Asia/Macau", label: "(UTC+08:00) China" },
  { value: "Asia/Ulaanbaatar", label: "(UTC+09:00) Ulaanbaatar" },
  { value: "Asia/Choibalsan", label: "(UTC+09:00) Choibalsan" },
  { value: "Pacific/Majuro", label: "(UTC+12:00) Majuro" },
  { value: "Pacific/Kwajalein", label: "(UTC+12:00) Kwajalein" },
  { value: "Europe/Belgrade", label: "(UTC+02:00) Central Europe" },
  { value: "Pacific/Pago_Pago", label: "(UTC-11:00) UTC-11" },
  { value: "Pacific/Wake", label: "(UTC+12:00) UTC+12" },
  { value: "Pacific/Honolulu", label: "(UTC-10:00) Hawaiian" },
  { value: "Europe/Malta", label: "(UTC+02:00) W. Europe" },
  { value: "Africa/Maputo", label: "(UTC+02:00) South Africa" },
  { value: "Indian/Maldives", label: "(UTC+05:00) West Asia" },
  { value: "America/Martinique", label: "(UTC-04:00) SA Western" },
  { value: "Pacific/Guam", label: "(UTC+10:00) West Pacific" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Antarctica/Macquarie", label: "(UTC+11:00) Central Pacific" },
  { value: "Australia/Hobart", label: "(UTC+11:00) Eastern - Hobart" },
  { value: "Australia/Sydney", label: "(UTC+11:00) Eastern - Sydney" },
  { value: "Australia/Brisbane", label: "(UTC+10:00) Eastern - Brisbane" },
  { value: "Australia/Adelaide", label: "(UTC+10:30) Central- Adelaide" },
  { value: "Australia/Darwin", label: "(UTC+09:30) Central - Darwin" },
  { value: "Australia/Perth", label: "(UTC+08:00) Western" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "Asia/Kuala_Lumpur", label: "(UTC+08:00) Kuala Lumpur" },
  { value: "America/Mexico_City", label: "(UTC-06:00) Central - Mexico City" },
  { value: "America/Cancun", label: "(UTC-05:00) Eastern" },
  { value: "America/Chihuahua", label: "(UTC-07:00) Mountain - Chihuahua" },
  { value: "America/Hermosillo", label: "(UTC-07:00) Mountain - Hermosillo" },
  { value: "America/Tijuana", label: "(UTC-07:00) Pacific" },
  { value: "Pacific/Efate", label: "(UTC+11:00) Central Pacific" },
  { value: "Europe/Paris", label: "(UTC+02:00) Romance" },
  { value: "America/Curacao", label: "(UTC-04:00) SA Western" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Asia/Kabul", label: "(UTC+04:30) Afghanistan" },
  { value: "Europe/Helsinki", label: "(UTC+03:00) FLE" },
  { value: "Europe/Helsinki", label: "(UTC+03:00) FLE" },
  { value: "Pacific/Fiji", label: "(UTC+12:00) Fiji" },
  { value: "Atlantic/Stanley", label: "(UTC-03:00) SA Eastern" },
  { value: "Pacific/Kosrae", label: "(UTC+11:00) Central Pacific" },
  { value: "Atlantic/Faroe", label: "(UTC+01:00) Faroe Time" },
  { value: "America/Managua", label: "(UTC-06:00) Central America" },
  { value: "Europe/Amsterdam", label: "(UTC+02:00) W. Europe" },
  { value: "Europe/Oslo", label: "(UTC+02:00) W. Europe" },
  { value: "Africa/Windhoek", label: "(UTC+02:00) Namibia" },
  { value: "Pacific/Noumea", label: "(UTC+11:00) Central Pacific" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "Pacific/Norfolk", label: "(UTC+11:00) Central Pacific" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "Pacific/Auckland", label: "(UTC+13:00) New Zealand" },
  { value: "Asia/Kathmandu", label: "(UTC+05:45) Nepal Time" },
  { value: "Pacific/Nauru", label: "(UTC+12:00) UTC+12" },
  { value: "Pacific/Niue", label: "(UTC-11:00) UTC-11" },
  { value: "Pacific/Rarotonga", label: "(UTC-10:00) Hawaiian" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Europe/Zurich", label: "(UTC+02:00) W. Europe" },
  { value: "America/Bogota", label: "(UTC-05:00) SA Pacific" },
  { value: "Asia/Shanghai", label: "(UTC+08:00) China" },
  { value: "Asia/Urumqi", label: "(UTC+06:00) Central Asia" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "America/Santiago", label: "(UTC-03:00) Santiago" },
  { value: "Pacific/Easter", label: "(UTC-05:00) Easter Island" },
  { value: "Indian/Cocos", label: "(UTC+06:30) Myanmar" },
  { value: "America/St_Johns", label: "(UTC-02:30) Newfoundland" },
  { value: "America/Halifax", label: "(UTC-03:00) Atlantic - Halifax" },
  { value: "America/Toronto", label: "(UTC-04:00) Eastern - Toronto" },
  { value: "America/Iqaluit", label: "(UTC-04:00) Eastern - Iqaluit" },
  { value: "America/Winnipeg", label: "(UTC-05:00) Central - Winnipeg" },
  { value: "America/Regina", label: "(UTC-06:00) Central - Regina" },
  { value: "America/Edmonton", label: "(UTC-06:00) Mountain - Edmonton" },
  { value: "America/Yellowknife", label: "(UTC-06:00) Mountain - Yellowknife" },
  { value: "America/Dawson_Creek", label: "(UTC-07:00) Dawson Creek" },
  { value: "America/Vancouver", label: "(UTC-07:00) Pacific - Vancouver" },
  { value: "America/Whitehorse", label: "(UTC-07:00) Pacific - Whitehorse" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "Africa/Maputo", label: "(UTC+02:00) South Africa" },
  { value: "Africa/Lagos", label: "(UTC+01:00) W. Central Africa" },
  { value: "Europe/Prague", label: "(UTC+02:00) Central Europe" },
  { value: "Asia/Nicosia", label: "(UTC+03:00) GTB" },
  { value: "Indian/Christmas", label: "(UTC+07:00) SE Asia" },
  { value: "America/Costa_Rica", label: "(UTC-06:00) Central America" },
  { value: "America/Curacao", label: "(UTC-04:00) SA Western" },
  { value: "Atlantic/Cape_Verde", label: "(UTC-01:00) Cape Verde" },
  { value: "America/Havana", label: "(UTC-04:00) Eastern" },
  { value: "Africa/Johannesburg", label: "(UTC+02:00) South Africa" },
  { value: "Asia/Damascus", label: "(UTC+02:00) Syria" },
  { value: "America/Curacao", label: "(UTC-04:00) SA Western" },
  { value: "Asia/Bishkek", label: "(UTC+06:00) Central Asia" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "Africa/Khartoum", label: "(UTC+03:00) E. Africa" },
  { value: "America/Paramaribo", label: "(UTC-03:00) SA Eastern" },
  { value: "Pacific/Tarawa", label: "(UTC+12:00) UTC+12" },
  { value: "Pacific/Enderbury", label: "(UTC+13:00) Tonga" },
  { value: "Pacific/Kiritimati", label: "(UTC+14:00) Line Islands" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) SE Asia" },
  { value: "America/El_Salvador", label: "(UTC-06:00) Central America" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Europe/Prague", label: "(UTC+02:00) Central Europe" },
  { value: "Europe/Oslo", label: "(UTC+02:00) W. Europe" },
  { value: "Europe/Belgrade", label: "(UTC+02:00) Central Europe" },
  { value: "Asia/Pyongyang", label: "(UTC+08:30) North Korea" },
  { value: "Asia/Riyadh", label: "(UTC+03:00) Arab" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Europe/Rome", label: "(UTC+02:00) W. Europe" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Indian/Mahe", label: "(UTC+04:00) Mauritius" },
  { value: "Pacific/Guadalcanal", label: "(UTC+11:00) Central Pacific" },
  { value: "Asia/Riyadh", label: "(UTC+03:00) Arab" },
  { value: "Asia/Singapore", label: "(UTC+08:00) Singapore" },
  { value: "Europe/Stockholm", label: "(UTC+02:00) W. Europe" },
  { value: "Africa/Khartoum", label: "(UTC+03:00) E. Africa" },
  { value: "America/Santo_Domingo", label: "(UTC-04:00) SA Western" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "Europe/Copenhagen", label: "(UTC+02:00) Romance" },
  { value: "Europe/Berlin", label: "(UTC+02:00) Berlin" },
  { value: "Asia/Riyadh", label: "(UTC+03:00) Arab" },
  { value: "Europe/Vienna", label: "(UTC+02:00) W. Europe" },
  { value: "Africa/Algiers", label: "(UTC+01:00) W. Central Africa" },
  { value: "America/New_York", label: "(UTC-04:00) Eastern" },
  { value: "America/Chicago", label: "(UTC-05:00) Central" },
  { value: "America/Denver", label: "(UTC-06:00) Mountain" },
  { value: "America/Phoenix", label: "(UTC-07:00) Mountain - AZ" },
  { value: "America/Los_Angeles", label: "(UTC-07:00) Pacific" },
  { value: "America/Anchorage", label: "(UTC-08:00) Alaskan" },
  { value: "Pacific/Honolulu", label: "(UTC-10:00) Hawaiian" },
  { value: "America/Montevideo", label: "(UTC-03:00) Montevideo" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "Indian/Mauritius", label: "(UTC+04:00) Mauritius" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Asia/Beirut", label: "(UTC+03:00) Middle East" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) SE Asia" },
  { value: "Pacific/Funafuti", label: "(UTC+12:00) UTC+12" },
  { value: "Asia/Taipei", label: "(UTC+08:00) Taipei" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Europe/Istanbul", label: "(UTC+03:00) Turkey" },
  { value: "Asia/Colombo", label: "(UTC+05:30) Sri Lanka" },
  { value: "Europe/Zurich", label: "(UTC+02:00) W. Europe" },
  { value: "Africa/Tunis", label: "(UTC+01:00) W. Central Africa" },
  { value: "Pacific/Tongatapu", label: "(UTC+13:00) Tonga" },
  { value: "Asia/Dili", label: "(UTC+09:00) Tokyo" },
  { value: "Asia/Ashgabat", label: "(UTC+05:00) West Asia" },
  { value: "Asia/Dushanbe", label: "(UTC+05:00) West Asia" },
  { value: "Africa/Johannesburg", label: "(UTC+02:00) South Africa" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) SE Asia" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Greenwich" },
  { value: "Africa/Ndjamena", label: "(UTC+01:00) W. Central Africa" },
  { value: "America/Grand_Turk", label: "(UTC-04:00) SA Western" },
  { value: "Africa/Tripoli", label: "(UTC+02:00) Libya" },
  { value: "Europe/Rome", label: "(UTC+02:00) W. Europe" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Asia/Dubai", label: "(UTC+04:00) Arabian" },
  { value: "America/Caracas", label: "(UTC-04:30) Venezuela" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "America/Port_of_Spain", label: "(UTC-04:00) SA Western" },
  { value: "Atlantic/Reykjavik", label: "(UTC+00:00) Greenwich" },
  { value: "Asia/Tehran", label: "(UTC+04:30) Iran" },
  { value: "Asia/Yerevan", label: "(UTC+04:00) Caucasus" },
  { value: "Europe/Rome", label: "(UTC+02:00) W. Europe" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) SE Asia" },
  { value: "Pacific/Pago_Pago", label: "(UTC-11:00) UTC-11" },
  { value: "America/Argentina/Salta", label: "(UTC-03:00) Argentina" },
  { value: "Europe/London", label: "(UTC+01:00) GMT" },
  { value: "Asia/Jerusalem", label: "(UTC+03:00) Israel" },
  { value: "Indian/Chagos", label: "(UTC+06:00) Central Asia" },
  { value: "Asia/Kolkata", label: "(UTC+05:30) India" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) E. Africa" },
  { value: "Asia/Baku", label: "(UTC+04:00) Azerbaijan" },
  { value: "Europe/Dublin", label: "(UTC+01:00) GMT" },
  { value: "Asia/Jakarta", label: "(UTC+07:00) Jakarta" },
  { value: "Asia/Makassar", label: "(UTC+08:00) Singapore" },
  { value: "Asia/Jayapura", label: "(UTC+09:00) Tokyo" },
  { value: "Europe/Kiev", label: "(UTC+03:00) Kiev" },
  { value: "Asia/Qatar", label: "(UTC+03:00) Arab" },
  { value: "Africa/Maputo", label: "(UTC+02:00) South Africa" },
  { value: "America/New_York", label: "(UTC-04:00) Eastern" },
  { value: "America/Chicago", label: "(UTC-05:00) Central" },
  { value: "America/Denver", label: "(UTC-06:00) Mountain" },
  { value: "America/Phoenix", label: "(UTC-07:00) Mountain - AZ" },
  { value: "America/Los_Angeles", label: "(UTC-07:00) Pacific" },
  { value: "America/Anchorage", label: "(UTC-08:00) Alaskan" },
  { value: "Pacific/Honolulu", label: "(UTC-10:00) Hawaiian"
  }
]