import { lazy } from 'react';
import { DEFAULT_PATHS } from './config';
import { RouteItemProps } from './routing/protocols/RouteIdentifier';
import { Role } from './pages/Auth/Login/hook/types';

const dashboard = lazy(() => import('./pages/Dashboard'));

const Login = {
  index: lazy(() => import('./pages/Auth/Login')),
  ForgotPassword: lazy(() => import('./pages/Auth/ForgotPassword/index')),
  Register: lazy(() => import('./pages/Auth/Register/index')),
  ResetPassword: lazy(() => import('./pages/Auth/ResetPassword/index')),
};

const ferramentas = {
  index: lazy(() => import('./views/apps/Apps')),
  calendar: lazy(() => import('./pages/Calendar')),
  chat: lazy(() => import('./pages/Chat')),
  diarioAlimentar: lazy(() => import('./pages/DiaryFood')),
  PatientControl: lazy(() => import('./pages/PatientControl')),
  FinancialControl: lazy(() => import('./pages/FinancialControl')),
  MetabolicTrakingLoose: lazy(() => import('./pages/MetabolicTrakingLoose')),
  Forum: lazy(() => import('./pages/Forum')),
  ForumTopic: lazy(() => import('./pages/Forum/Topic')),
  NutritionalBlades: lazy(() => import('./pages/NutritionalBlades')),
  form: lazy(() => import('./pages/FormLoose')),
  formResponse: lazy(() => import('./pages/FormResponsePage')),
  MySettings: lazy(() => import('./pages/MySettings')),
  ProfessionalMeet: lazy(() => import('./pages/ProfessionalMeet')),
  PanelPatient: lazy(() => import('./pages/PanelPatient')),
  ProfessionalWebsite: lazy(() => import('./pages/ProfessionalWebsite')),
  // RoadMap: lazy(() => import('./pages/RoadMap')),
  // AdminPanel: lazy(() => import('./pages/AdminPanel')),
  // ProfessionalWebSiteSchedule: lazy(() => import('./pages/ProfessionalWebSiteSchedule')),
};

const pages = {
  index: lazy(() => import('./views/pages/Pages')),
  authentication: {
    login: lazy(() => import('./pages/authentication/Login')),
    register: lazy(() => import('./pages/authentication/Register')),
    forgotPassword: lazy(() => import('./pages/authentication/ForgotPassword')),
    resetPassword: lazy(() => import('./pages/authentication/ResetPassword')),
  },

  classicEatingPlan: lazy(() => import('./pages/ClassicEatingPlan')),
  classicEatingPlanTemplate: lazy(() => import('./pages/classicEatingPlanTemplate')),
  equivalentEatingPlan: lazy(() => import('./pages/EquivalentEatingPlan')),
  anthropometricAssessment: lazy(() => import('./pages/AnthropometricAssessment/Adult')),
  anthropometricAssessmentComparative: lazy(() => import('./pages/AnthropometricAssessment/AdultComparative')),
  anthropometricAssessment0a5years: lazy(() => import('./pages/AnthropometricAssessment/Children0To5Years')),
  anthropometricAssessment0a5yearsComparative: lazy(() => import('./pages/AnthropometricAssessment/Children0To5YearsComparative')),
  anthropometricAssessment5a19years: lazy(() => import('./pages/AnthropometricAssessment/Children5To19Years')),
  anthropometricAssessment5a19yearsComparative: lazy(() => import('./pages/AnthropometricAssessment/Children5To19YearsComparative')),
  anthropometricAssessmentPregnantComparative: lazy(() => import('./pages/AnthropometricAssessment/PregnantComparative')),
  anthropometricAssessmentPregnancy: lazy(() => import('./pages/AnthropometricAssessment/Pregnant')),
  anthropometricAssessmentBioimpedance: lazy(() => import('./pages/AnthropometricAssessment/Bioimpedance')),
  anthropometricAssessmentBioimpedanceComparative: lazy(() => import('./pages/AnthropometricAssessment/BioimpedanceComparative')),
  requestingExams: lazy(() => import('./pages/RequestingExams')),
  requestingExamsComparative: lazy(() => import('./pages/RequestingExamsComparative')),
  reminder: lazy(() => import('./pages/Reminder')),
  Recipe: lazy(() => import('./pages/Recipe')),
  CaloricExpenditure: lazy(() => import('./pages/CaloricExpenditure')),
  FormPatientRegistered: lazy(() => import('./pages/FormPatientRegistered')),
  Anamnesis: lazy(() => import('./pages/Anamnesis/')),
  NutritionalGuidance: lazy(() => import('./pages/NutritionalGuidance/')),
  MedicalRecord: lazy(() => import('./pages/MedicalRecord/')),
  QualitativeEatingPlan: lazy(() => import('./pages/QualitativeEatingPlan/')),
  MySettings: lazy(() => import('./pages/MySettings/')),
  ManipulatedFormulas: lazy(() => import('./pages/ManipulatedFormulas')),
  MetabolicTracking: lazy(() => import('./pages/MetabolicTracking')),
  SignSymptom: lazy(() => import('./pages/SignSymptom')),
};

const patientMenu = {
  index: lazy(() => import('./pages/PatientMenu')),
  classicEatingPlan: lazy(() => import('./pages/PatientMenu/classic-eating-plan')),
  equivalentEatingPlan: lazy(() => import('./pages/PatientMenu/equivalent-eating-plan')),
  anthropometricAssessment: lazy(() => import('./pages/PatientMenu/anthropometric-assessment')),
  Register: lazy(() => import('./pages/Auth/Register/index')),
  ResetPassword: lazy(() => import('./pages/Auth/ResetPassword/index')),
  sendingMaterials: lazy(() => import('./pages/PatientMenu/sending-materials')),
  requestingExams: lazy(() => import('./pages/PatientMenu/requesting-exams')),
  reminder: lazy(() => import('./pages/PatientMenu/reminder')),
  Recipe: lazy(() => import('./pages/PatientMenu/recipe')),
  CaloricExpenditure: lazy(() => import('./pages/PatientMenu/caloric-expenditure')),
  FormPatientRegistered: lazy(() => import('./pages/PatientMenu/form-patient-registered')),
  Anamnesis: lazy(() => import('./pages/PatientMenu/anamnesis-patient')),
  NutritionalGuidance: lazy(() => import('./pages/PatientMenu/nutritional-guidance')),
  MedicalRecord: lazy(() => import('./pages/PatientMenu/medical-record')),
  MobileManagement: lazy(() => import('./pages/PatientMenu/mobile-management')),
  AttachmentMaterials: lazy(() => import('./pages/PatientMenu/attachment-materials')),
  QualitativeEatingPlan: lazy(() => import('./pages/PatientMenu/qualitative-eating-plan')),
  ManipulatedFormulas: lazy(() => import('./pages/PatientMenu/manipulated-formulas')),
  HistoryPatientFolder: lazy(() => import('./pages/PatientMenu/patient-folder')),
  FormCreate: lazy(() => import('./pages/FormLoose/FormBuilder')),
  FormResponse: lazy(() => import('./pages/FormResponsePage')),
  MySettings: lazy(() => import('./pages/MySettings/')),
  Receipt: lazy(() => import('./pages/PatientMenu/receipt')),
  AttendanceCertificate: lazy(() => import('./pages/PatientMenu/attendance-certificate')),
  Goals: lazy(() => import('./pages/PatientMenu/goals')),
  ChecklistConduct: lazy(() => import('./pages/PatientMenu/checklist-conduct')),
  MetabolicTracking: lazy(() => import('./pages/PatientMenu/metabolic-tracking')),
  SignsSymptoms: lazy(() => import('./pages/PatientMenu/signs-symptoms')),
  ComparativePhotos: lazy(() => import('./pages/PatientMenu/comparative-photos')),
  HydrationAlert: lazy(() => import('./pages/PatientMenu/hydration-alert')),
  CarePlan: lazy(() => import('./pages/PatientMenu/care-plan')),
  Budget: lazy(() => import('./pages/PatientMenu/budget')),
};

const myMaterials = {
  index: lazy(() => import('./pages/MyMaterials')),
  myAttachments: lazy(() => import('./pages/MyMaterials/my-attachments')),
  classicEatingPlan: lazy(() => import('./pages/MyMaterials/classic-eating-plan')),
  myMeals: lazy(() => import('./pages/MyMaterials/my-meals')),
  myQualitativeMeals: lazy(() => import('./pages/MyMaterials/my-qualitative-meals')),
  myAnamnesis: lazy(() => import('./pages/MyMaterials/my-anamnesis')),
  MyFoods: lazy(() => import('./pages/MyMaterials/my-foods')),
  MyEquivalentFoods: lazy(() => import('./pages/MyMaterials/my-equivalent-foods')),
  ReplacementList: lazy(() => import('./pages/MyMaterials/replacement-list')),
  MyNutritionalGuidance: lazy(() => import('./pages/MyMaterials/my-orientation')),
  MyComments: lazy(() => import('./pages/MyMaterials/my-comments')),
  MyRecipes: lazy(() => import('./pages/MyMaterials/my-recipes')),
  MyExams: lazy(() => import('./pages/MyMaterials/my-exams')),
  MyManipulatedFormulas: lazy(() => import('./pages/MyMaterials/manipulated-formulas')),
  MyGoals: lazy(() => import('./pages/MyMaterials/my-goals')),
  MyChecklists: lazy(() => import('./pages/MyMaterials/checklist-conduct')),
};

export const appRoot = DEFAULT_PATHS.APP.endsWith('/') ? DEFAULT_PATHS.APP.slice(0, DEFAULT_PATHS.APP.length - 1) : DEFAULT_PATHS.APP;

export interface RoutesAndMenuItems {
  mainMenuItems: RouteItemProps[];
  sidebarItems: RouteItemProps[];
}

const routesAndMenuItems: RoutesAndMenuItems = {
  mainMenuItems: [
    {
      path: DEFAULT_PATHS.APP,
      label: 'home',
      icon: 'home',
      component: dashboard,
      roles: [],
    },
    {
      path: `${appRoot}/calendar`,
      component: ferramentas.calendar,
      hideInMenu: true,
      roles: [Role.SECRETARY],
    },
    {
      path: `${appRoot}/menu-paciente/:id`,
      label: 'menu-paciente',
      component: patientMenu.index,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
      subs: [
        { path: '/plano-alimentar-classico', component: patientMenu.classicEatingPlan, index: true },
        { path: '/plano-alimentar-equivalante', component: patientMenu.equivalentEatingPlan },
        { path: '/avaliacao-antropometrica', component: patientMenu.anthropometricAssessment },
        { path: '/solicitacao-exames', component: patientMenu.requestingExams },
        { path: '/envio-de-materiais', component: patientMenu.sendingMaterials },
        { path: '/recordatorio', component: patientMenu.reminder },
        { path: '/receitas-culinarias', component: patientMenu.Recipe },
        { path: '/gasto-calorico', component: patientMenu.CaloricExpenditure },
        { path: '/formulario-pre-consulta', component: patientMenu.FormPatientRegistered },
        { path: '/meus-dados', component: patientMenu.MySettings },
        { path: '/anamnese', component: patientMenu.Anamnesis },
        { path: '/orientacoes', component: patientMenu.NutritionalGuidance },
        { path: '/prontuario', component: patientMenu.MedicalRecord },
        { path: '/configuracao-app', component: patientMenu.MobileManagement },
        { path: '/anexo-materiais', component: patientMenu.AttachmentMaterials },
        { path: '/plano-alimentar-qualitativo', component: patientMenu.QualitativeEatingPlan },
        { path: '/recibo', component: patientMenu.Receipt },
        { path: '/atestado', component: patientMenu.AttendanceCertificate },
        { path: '/metas', component: patientMenu.Goals },
        { path: '/check-list', component: patientMenu.ChecklistConduct },
        { path: '/rastreamento-metabolico', component: patientMenu.MetabolicTracking },
        { path: '/sinais-sintomas', component: patientMenu.SignsSymptoms },
        { path: '/fotos-comparativas', component: patientMenu.ComparativePhotos },
        { path: '/alerta-hidratacao', component: patientMenu.HydrationAlert },
        { path: '/formulas-manipuladas', component: patientMenu.ManipulatedFormulas },
        { path: '/pasta-do-paciente', component: patientMenu.HistoryPatientFolder },
        { path: '/plano-de-tratamento', component: patientMenu.CarePlan },
        { path: '/orcamento', component: patientMenu.Budget },
      ],
    },
    {
      path: `${appRoot}/plano-alimentar-classico/:id`,
      label: 'menu.plano-alimentar-classico',
      component: pages.classicEatingPlan,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/modelo-plano-alimentar-classico/:id`,
      label: 'menu.plano-alimentar-classico',
      component: pages.classicEatingPlanTemplate,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/plano-alimentar-equivalente/:id`,
      label: 'menu.plano-alimentar-equivalente',
      component: pages.equivalentEatingPlan,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica/:id`,
      label: 'menu.avaliacao-antropometrica',
      component: pages.anthropometricAssessment,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica-comparativo/:id`,
      label: 'menu.avaliacao-antropometrica-comparativo',
      component: pages.anthropometricAssessmentComparative,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica-infantil/:id`,
      label: 'menu.avaliacao-antropometrica-infantil',
      component: pages.anthropometricAssessment0a5years,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica-comparativo/paciente-0-a-5-anos/:id`,
      label: 'menu.avaliacao-antropometrica-infantil-comparativo',
      component: pages.anthropometricAssessment0a5yearsComparative,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica-adolescentes/:id`,
      label: 'menu.avaliacao-antropometrica-adolescentes',
      component: pages.anthropometricAssessment5a19years,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica-comparativo/paciente-5-a-19-anos/:id`,
      label: 'menu.avaliacao-antropometrica-adolescentes-comparativo',
      component: pages.anthropometricAssessment5a19yearsComparative,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica-gestante/:id`,
      label: 'menu.avaliacao-antropometrica-gestante',
      component: pages.anthropometricAssessmentPregnancy,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica-comparativo/paciente-gestante/:id`,
      label: 'menu.solicitacao-exames-paciente',
      component: pages.anthropometricAssessmentPregnantComparative,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica-bioimpedancia/:id`,
      label: 'menu.avaliacao-antropometrica-gestante',
      component: pages.anthropometricAssessmentBioimpedance,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/avaliacao-antropometrica-comparativo/bioimpedancia/:id`,
      label: 'menu.avaliacao-antropometrica-gestante',
      component: pages.anthropometricAssessmentBioimpedanceComparative,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/solicitacao-exames/:id`,
      label: 'menu.solicitacao-exames',
      component: pages.requestingExams,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/solicitacao-exames/paciente/:id`,
      label: 'menu.solicitacao-exames-paciente',
      component: pages.requestingExamsComparative,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/recordatorio/:id`,
      label: 'menu.recordatorio',
      component: pages.reminder,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/receita-culinaria/:id`,
      label: 'menu.receita-culinaria',
      component: pages.Recipe,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/gasto-calorico/:id`,
      label: 'menu.gasto-calorico',
      component: pages.CaloricExpenditure,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/formulario-pre-consulta-paciente-cadastrado/:id/:patientId`,
      label: 'menu.formulario-pre-consulta-paciente-cadastrado',
      component: pages.FormPatientRegistered,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/formulario-pre-consulta-paciente-cadastrado/novo/:patientId`,
      label: 'menu.formulario-pre-consulta-paciente-cadastrado',
      component: pages.FormPatientRegistered,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/anamnese/:id`,
      label: 'menu.anamnese',
      component: pages.Anamnesis,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/orientacoes/:id`,
      label: 'menu.orientacoes',
      component: pages.NutritionalGuidance,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/prontuario/:id`,
      label: 'menu.prontuario',
      component: pages.MedicalRecord,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/plano-alimentar-qualitativo/:id`,
      label: 'menu.plano-alimentar-qualitativo',
      component: pages.QualitativeEatingPlan,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/formulas-manipuladas/:id`,
      label: 'formulas-manipuladas',
      component: pages.ManipulatedFormulas,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/rastreamento-metabolico/:id`,
      label: 'rastreamento-metabolico',
      component: pages.MetabolicTracking,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/sinais-sintomas/:id`,
      label: 'sinais-sintomas',
      component: pages.SignSymptom,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/meus-dados`,
      label: 'menu.meus-dados',
      component: ferramentas.MySettings,
      hideInMenu: true,
      roles: [Role.PROFESSIONAL],
    },
    {
      path: `${appRoot}/ferramentas`,
      label: 'menu.apps',
      icon: 'screen',
      roles: [Role.PROFESSIONAL],
      subs: [
        { path: '/calendar', label: 'menu.calendar', component: ferramentas.calendar },
        { path: '/diario-alimentar', label: 'menu.diario-alimentar', component: ferramentas.diarioAlimentar },
        {
          path: '/forum', label: 'menu.forum', subs: [
            { path: '/', label: 'menu.forum', component: ferramentas.Forum, hideInMenu: true, index: true },
            { path: '/:id', label: 'menu.forum', component: ferramentas.ForumTopic, hideInMenu: true },
          ]
        },
        { path: '/laminas-nutricionais', label: 'menu.laminas-nutricionais', component: ferramentas.NutritionalBlades },
        { path: '/chat', label: 'menu.chat', component: ferramentas.chat },
        { path: '/chat/:id', label: 'menu.chat', component: ferramentas.chat, hideInMenu: true },
        { path: '/meet/:token', label: 'menu.videochamada', component: ferramentas.ProfessionalMeet },
        { path: '/criar-formulario', component: patientMenu.FormCreate },
        { path: '/editar-formulario/:id', component: patientMenu.FormCreate },
        { path: '/editar-formulario/:id', component: patientMenu.FormCreate },
        { path: '/controle-pacientes', label: 'menu.controle-pacientes', component: ferramentas.PatientControl },
        { path: '/controle-financeiro', label: 'menu.controle-financeiro', component: ferramentas.FinancialControl },
        { path: '/site', label: 'menu.site', component: ferramentas.ProfessionalWebsite },
        // { path: '/admin', label: 'menu.admin', component: ferramentas.AdminPanel },
        // { path: '/road-map', label: 'menu.road-map', component: ferramentas.RoadMap },
        // { path: '/admin', label: 'menu.admin', component: ferramentas.AdminPanel },
        // { path: '/site-agenda', label: 'menu.site-agenda', component: ferramentas.ProfessionalWebSiteSchedule },
      ],
    },
    {
      path: `${appRoot}/pages`,
      label: 'menu.consultorio',
      icon: 'notebook-1',
      roles: [Role.PROFESSIONAL],
      subs: [
        {
          path: '/meus-materiais/',
          label: 'menu.meus-materiais',
          component: myMaterials.index,
          subs: [
            { path: '/meus-anexos', component: myMaterials.myAttachments, index: true },
            { path: '/meus-planos-alimentares', component: myMaterials.classicEatingPlan, index: false },
            { path: '/minhas-refeicoes', component: myMaterials.myMeals, index: false },
            { path: '/minhas-refeicoes-qualitativas', component: myMaterials.myQualitativeMeals, index: false },
            { path: '/minhas-anamneses', component: myMaterials.myAnamnesis, index: false },
            { path: '/meus-alimentos', component: myMaterials.MyFoods, index: false },
            { path: '/meus-alimentos-equivalentes', component: myMaterials.MyEquivalentFoods, index: false },
            { path: '/minhas-listas-de-substituicao', component: myMaterials.ReplacementList, index: false },
            { path: '/minhas-orientacoes', component: myMaterials.MyNutritionalGuidance, index: false },
            { path: '/meus-comentarios', component: myMaterials.MyComments, index: false },
            { path: '/minhas-receitas', component: myMaterials.MyRecipes, index: false },
            { path: '/meus-exames', component: myMaterials.MyExams, index: false },
            { path: '/minhas-formulas-manipuladas', component: myMaterials.MyManipulatedFormulas, index: false },
            { path: '/minhas-metas', component: myMaterials.MyGoals, index: false },
            { path: '/minhas-listas-de-conduta', component: myMaterials.MyChecklists, index: false },
          ],
        },
        { path: '/rastreamento-metabolico-avulso', label: 'menu.rastreamento-metabolico-avulso', component: ferramentas.MetabolicTrakingLoose },
        { path: '/formulario-pre-consulta', label: 'menu.formulario-pre-consulta', component: ferramentas.form },
      ],
    },
  ],

  sidebarItems: [
    { path: '#connections', label: 'menu.connections', icon: 'diagram-1', hideInRoute: true },
    { path: '#bookmarks', label: 'menu.bookmarks', icon: 'bookmark', hideInRoute: true },
    { path: '#requests', label: 'menu.requests', icon: 'diagram-2', hideInRoute: true },
    {
      path: '#account',
      label: 'menu.account',
      icon: 'user',
      hideInRoute: true,
      subs: [
        { path: '/settings', label: 'menu.settings', icon: 'gear', hideInRoute: true },
        { path: '/password', label: 'menu.password', icon: 'lock-off', hideInRoute: true },
        { path: '/devices', label: 'menu.devices', icon: 'mobile', hideInRoute: true },
      ],
    },
    {
      path: '#notifications',
      label: 'menu.notifications',
      icon: 'notification',
      hideInRoute: true,
      subs: [
        { path: '/email', label: 'menu.email', icon: 'email', hideInRoute: true },
        { path: '/sms', label: 'menu.sms', icon: 'message', hideInRoute: true },
      ],
    },
    {
      path: '#downloads',
      label: 'menu.downloads',
      icon: 'download',
      hideInRoute: true,
      subs: [
        { path: '/documents', label: 'menu.documents', icon: 'file-text', hideInRoute: true },
        { path: '/images', label: 'menu.images', icon: 'file-image', hideInRoute: true },
        { path: '/videos', label: 'menu.videos', icon: 'file-video', hideInRoute: true },
      ],
    },
  ],
};
export default routesAndMenuItems;
